### ISSUE TITLE
tslog should not modify the Error prototype

### ISSUE THREAD

**Issue by jonahsnider** [fullstack-build/tslog#92] opened 2021-03-02 17:38 UTC
https://github.com/watson/error-callsites/blob/1d6e6cc416b56d535c608ed77980867bb7b345c9/index.js#L8-L21

https://github.com/fullstack-build/tslog/blob/77ab7c9331d0bc6f627fa7a4e45a4eebc8908a01/src/CallSitesHelper.ts#L64-L78

tslog should not modify the global Error prototype. If modifying the prototype is necessary for certain features it should be explicitly enabled with an option.

This can cause issues in otherwise working code. For example, in a working API server, introducing tslog caused error handling code to crash the app instead of responding to an HTTP request.

**Comment by terehov** [comment] 2021-03-11 13:29
Thank you for your input. We use this to access native v8 stack information. I will put some thought into this issue.

**Comment by eugene1g** [comment] 2021-07-30 18:06
Somewhat related - Node has native support for sourcemaps (via `--enable-source-maps`), and this feature breaks as soon as `tslog` is `require`d anywhere the application because `prepareStackTrace` is hijacked by the library. We use TypeScript, and have to add  `delete Error.prepareStackTrace` immediately after including `tslog` to restore the expected behavior.

**Comment by terehov** [comment] 2021-07-30 18:39
@eugene1g Thank you for this hint!

**Comment by terehov** [comment] 2022-09-30 12:47
There is a new, completely rewritten version (4.0) which does not interfere with the Error object any more. 
And yes, we are now completely dependency free and use the native supported source maps. 
Give it a go and let me know if that solves your problem: 

- `npm i tslog@next`

- and run it with `node --enable-source-maps` or for TypeScript `node --enable-source-maps --experimental-specifier-resolution=node --no-warnings --loader ts-node/esm`

Thank you.

**Comment by terehov** [comment] 2022-11-15 18:22
V4 is released now, so I'm going to close this issue. 
Feel free to open a new one if V4 didn't solve it for you. 

Here are the docs: [tslog.js.org](https://tslog.js.org)

**Closed by terehov** 2022-11-15 18:22 UTC

**Comment by ShinJustinHolly3317** [comment] 2022-12-20 06:09
still facing this issue with the command option you provide..

**Comment by terehov** [comment] 2022-12-20 06:33
@ShinJustinHolly3317 More details please. Did you upgrade to V4? It won’t help with V3.

**Comment by ShinJustinHolly3317** [comment] 2022-12-20 07:57
sorry for my ambiguous question, and just ignore it.

I'm using v3.3.0 currently with Typescript, 
and what I'm facing is that the logger always show the property `stack` in every class inherits from native Error class.

Is there any way to prevent the `stack` property showing? Cause from our development convention, we use our custom Error class as response (we're using Express as server framework).

**Comment by terehov** [comment] 2022-12-20 08:07
@ShinJustinHolly3317 
I understand your request, and that's why I rewrote `tslog` completely to not interfere with the native Error instance any more, which was used to access the underlying V8 meta information.

Is there a reason why you prefer to stick to V3 instead of upgrading to V4?

**Comment by ShinJustinHolly3317** [comment] 2022-12-20 08:43
@terehov 
Cause there will be some check and migration work.
Just asking if there is any other way to work around.

and also I did't find explanation or example for `overwritingConsole`.
Just curious if this option still works?

**Comment by terehov** [comment] 2022-12-20 08:52
> @terehov Cause there will be some check and migration work (team legacy). Just asking if there is any other way to work around.

I see. I can help you with migration of tslog, if it helps. 

> and also I did't find explanation or example for `overwritingConsole`. Just curious if this option still works?

Unfortunately not, since console is the default output in V4, plus you can easily add this functionality from outside the library.

**Comment by ShinJustinHolly3317** [comment] 2022-12-20 09:08
> > @terehov Cause there will be some check and migration work (team legacy). Just asking if there is any other way to work around.
> 
> I see. I can help you with migration of tslog, if it helps.
> 
> > and also I did't find explanation or example for `overwritingConsole`. Just curious if this option still works?
> 
> Unfortunately not, since console is the default output in V4, plus you can easily add this functionality from outside the library.

Thank you, helps a lot.
Let me have a discussion with my team which way is better.
