### ISSUE TITLE
Bug: Method names for async functions not showing

### ISSUE THREAD

**Issue by sfsr12** [fullstack-build/tslog#65] opened 2020-11-18 02:48 UTC
**Describe the bug**
When a log is written from an async function it does not have a method name associated with it in the output.  This might be an issue with how async/await works - or how I implement so not sure this is a tslog issue or not?

```
2020-11-18 02:31:14.309.000      INFO   [src\main.ts:5 testSync]                testSync - Yep    
2020-11-18 02:31:14.338.000      INFO   [src\main.ts:8]                 testAsync - Nope
```

**To Reproduce**
```ts
import { Logger } from 'tslog';
const logger = new Logger();

const testSync = () => {
  logger.info('testSync - Yep');
};
const testAsync = async () => {
  logger.info('testAsync - Nope');
};

(async () => {
  testSync();
  await testAsync();
})();
```

**Expected behavior**
I would expect the output to show `[src\main.ts:8 testAsync] ` not just `[src\main.ts:8]`.

**Screenshots**
![image](https://user-images.githubusercontent.com/13442518/99476432-cb79c180-290d-11eb-8645-a250431593b4.png)

**Additional context**

**Node.js Version**
v15.2.1

**OS incl. Version**
Windows 10

**Comment by sfsr12** [comment] 2020-11-19 02:06
A bit more info on this that I found while messing with stuff.  It looks like you can change this:

LoggerWithoutCallSite.ts
```js
    const functionName: string =
      this.settings.displayFunctionName === true
        ? logObject.isConstructor
          ? ` ${logObject.typeName}.constructor`
          : logObject.methodName != null
          ? ` ${logObject.typeName}.${logObject.methodName}`
          : logObject.functionName != null
          ? ` ${logObject.functionName}`
          : ""
        : "";
```
```js
    const functionName: string =
      this.settings.displayFunctionName === true
        ? logObject.isConstructor
          ? ` ${logObject.typeName}.constructor`
          : logObject.methodName != null
          ? ` ${logObject.typeName}.${logObject.methodName}`
          : logObject.functionName != null
          ? ` ${logObject.functionName}`
          : logObject.typeName !== null
          ? `${logObject.typeName}.<anonymous>`
          : ""
        : "";
```

and it will give results that mirror (I think) the error stack.

**Comment by sfsr12** [comment] 2020-11-19 04:44
I found another solution/answer to what was wrong.  I was targeting es5 in my tsconfig.  Changing that to target es2018 resolves the issue.

```json
{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "lib": ["es6", "dom"],
    "allowJs": true,
    "outDir": "build",
    "rootDir": "src",
    "strict": true,
    "noImplicitAny": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "sourceMap": true,
    "typeRoots": ["./@types", "./node_modules/@types"]
  },
  "include": ["src/**/*"],
  "exclude": ["src/**/*.spec.ts"]
}
```

**Comment by terehov** [comment] 2020-11-24 15:40
Hi @sfsr12,

I can reproduce it with `target`: `es5`, `es2015` and `es2016` and it starts working from `es2017` onwards. 
Why would you want to target such an old ES version? 

PS: Thank you for your suggestion regarding `functionName`, I am going to ad it with the new release. I think it's good practice to output `<anonymous>`  in that case.

**Comment by terehov** [comment] 2020-11-24 15:42
I am going to close this issue because you've already found a solution. Let me know if you have a valid use case for targeting `es5`.

**Closed by terehov** 2020-11-24 15:42 UTC
Labels: bug

**Comment by sfsr12** [comment] 2020-11-24 16:29
No, that was a mistake to target the old version - was converting old projects.
