### ISSUE TITLE
Bug: Instantiating logger breaks console.error()

### ISSUE THREAD

**Issue by flybayer** [fullstack-build/tslog#51] opened 2020-10-13 01:11 UTC
**Describe the bug**
We are using tslog inside [Blitz.js](https://github.com/blitz-js/blitz). It's really great, but noticed that it's causing a regression because it breaks the default behavior of `console.error`.

Before instantiating a tslog logger, `console.error(new Error("Hello"))` prints the following:

```
Error: Hello
    at Test (webpack-internal:///./pages/ssr.tsx:92:17)
    ...redacted
```

But after instantiating a logger,  `console.error(new Error("Hello"))` prints this:
```
[Error: Hello]
```

As you can see, this is very bad because you can't tell where the error is from. 

In this case, third-party code is using `console.error`, so it's not something we can change.

**To Reproduce**
1. Run `console.error(new Error("Hello"))`
2. See error with stack trace
3. Instantiate logger: `new Logger()`
1. Run `console.error(new Error("Hello"))`
1. See there is no stack trace.

**Node.js Version**
Node v12

**OS incl. Version**
```
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 5.43 GB / 64.00 GB
    Shell: 3.1.2 - /usr/local/bin/fish
```

**Comment by terehov** [comment] 2020-10-13 05:26
Thank you for reporting this. 
I’ll look into it today!

**Comment by terehov** [comment] 2020-10-13 09:38
Hey @flybayer,

I am flattered that you guys decided to use `tslog`. I am as well considering using Blitz.js for one of my projects. 
Nice work! :-)  

Unfortunately, I am not able to reproduce your error. 

This is how it looks on my Node 14: 
<img width="1792" alt="Screenshot 2020-10-13 at 12 29 13" src="https://user-images.githubusercontent.com/490885/95843248-2852ec80-0d50-11eb-9bee-21fd65515f89.png">

And on Node 10: 
<img width="1792" alt="Screenshot 2020-10-13 at 12 31 35" src="https://user-images.githubusercontent.com/490885/95843277-30129100-0d50-11eb-80a7-8655dec222e3.png">

In fact, I don't really touch `console.error` as long as you don't set `overwriteConsole: true`. 
This is how it looks when you do: 
<img width="1792" alt="Screenshot 2020-10-13 at 12 34 48" src="https://user-images.githubusercontent.com/490885/95843549-8089ee80-0d50-11eb-9b65-b577a8117834.png">

Can you please provide some more details that could help to reproduce that behavior? Which Node.js version do you use? Do you you `ts-node` or typescript in general. Thanks!

**Comment by flybayer** [comment] 2020-10-14 01:05
@terehov here's a reproduction: https://codesandbox.io/s/hungry-montalcini-3ii6c?file=/pages/index.js

Turns out simply importing the logger is enough to do it.

**Comment by terehov** [comment] 2020-10-14 14:16
Thank you very much, that was really helpful! 
I have found and fixed the issue. Just need to update the tests to remain at 100% coverage. 
Expect an update today or at the latest tomorrow.

**Comment by terehov** [comment] 2020-10-15 10:05
I have just released a patch version `2.9.1` that seems to solve this issue: 

<img width="1792" alt="Screenshot 2020-10-15 at 13 04 51" src="https://user-images.githubusercontent.com/490885/96109165-0b9ced00-0ee7-11eb-95a3-b309e5e9b0c5.png">

**Comment by flybayer** [comment] 2020-10-15 15:38
Sweet, thanks! Will test this in Blitz.

**Comment by terehov** [comment] 2020-10-17 05:19
I assume this issue has been resolved and going to close it.

**Closed by terehov** 2020-10-17 05:19 UTC
Labels: bug
