### ISSUE TITLE
exception when loging errorr: [BUG]

### ISSUE THREAD

**Issue by tomer-refundit** [fullstack-build/tslog#27] opened 2020-06-29 07:43 UTC
**Describe the bug**
when trying to log error object an exception is thrown

**To Reproduce**
write in the code the following code:
logger.error(new Error())

**Expected behavior**
should work

**Additional context**
TypeError: stack.reduce is not a function
    at Function.getCallSites (/my-app/node_modules/tslog/src/LoggerHelper.ts:57:15)
    at Logger._buildErrorObject (/my-app/node_modules/tslog/src/index.ts:451:60)
    at /my-app/node_modules/tslog/src/index.ts:428:16
    at Array.forEach (<anonymous>)
    at Logger._buildLogObject (/my-app/node_modules/tslog/src/index.ts:425:28)
    at Logger._handleLog (/my-app/node_modules/tslog/src/index.ts:351:40)
    at Logger.error (/my-app/node_modules/tslog/src/index.ts:304:28)

this happend because error.stack is string and not array

 const stack: NodeJS.CallSite[] =
      error == null
        ? ((new Error().stack as unknown) as NodeJS.CallSite[]).slice(1)
        : ((error.stack as unknown) as NodeJS.CallSite[]);

**Comment by terehov** [comment] 2020-06-29 17:36
Hey @tomer-refundit,

I can't reproduce it. Can you pls fill up the versions you are using of tslog, Node.js, TypeScript, OS, ts-node

This is how it looks on my end: 

<img width="542" alt="image" src="https://user-images.githubusercontent.com/490885/86037579-db1c6a80-ba3f-11ea-90aa-b9931d9e68b6.png">

**Comment by tomer-refundit** [comment] 2020-06-30 08:43
its really strange.
this error only happens when i am debugging with break points. i dont know why...
if you put breake point at LoggerHelper.getCallSites you will see it
tslog: 2.5.0
node: v14.2.0
typescript: 3.9.5
OS: mac
ts-node: not used

**Comment by terehov** [comment] 2020-07-07 23:25
@tomer-refundit 
I guess this issue has also been fixed with `2.6.1`. Please let me know if it's not the case. 
Thanks!

**Closed by terehov** 2020-07-07 23:25 UTC
Labels: bug
